FROM nginx
RUN echo '<h1>Hello,Docker ,here is jeff ' > /usr/share/nginx/html/index.html
# Shell form
CMD echo $HOME
# Exec form
#CMD ["sh","-c","echo $HOME"]
# docker run --name web2  nginx:v2
# /root ,it console
# e.g build an centos node_modules docker,rewrite it default program to install exisitng folder